import { Component } from 'react';

import kpGetMoviesList from '../../utils/kpGetMoviesList';
import MoviesList from '../MoviesList';

const list = await kpGetMoviesList('ghost in');
const debugList = {
  docs: [
    {
      internalNames: [
        'Водный мир',
        'Waterworld',
        'Olum Ha-Mayim',
        'Mundo acuatico',
        'Un monde sans terre',
        'ウォーターワールド',
        'ウォーターワールド：1995',
      ],
      name: 'Водный мир',
      alternativeName: 'Waterworld',
      enName: '',
      year: 1995,
      genres: [
        { name: 'фантастика' },
        { name: 'боевик' },
        { name: 'приключения' },
      ],
      countries: [{ name: 'США' }],
      releaseYears: [],
      id: 8165,
      externalId: {
        imdb: 'tt0114898',
        tmdb: 9804,
        kpHD: '4ab611bac07879a89897d04b009fed05',
      },
      names: [
        { name: 'Водный мир' },
        { name: 'Waterworld' },
        {
          name: 'Olum Ha-Mayim',
          language: 'IL',
          type: 'Romanized title',
        },
        { name: 'Mundo acuatico', language: 'ES', type: null },
        {
          name: 'Un monde sans terre',
          language: 'CA',
          type: 'Français',
        },
        { name: 'ウォーターワールド', language: 'JP', type: null },
        {
          name: 'ウォーターワールド：1995',
          language: 'JP',
          type: null,
        },
      ],
      type: 'movie',
      description:
        'В далеком будущем полярные снега растаяли, покрыв практически всю Землю водой. И хотя ходят легенды, что где-то остался кусочек пригодной для жизни суши, её до сих пор никто не смог найти. \n\nНа Атолл приплывает Моряк. Он хочет продать землю, добытую при нырянии, но его принимают за шпиона «курильщиков» – самых опасных бандитов Водного мира. При помощи девушки Хелен и маленькой девочки Энолы ему удается избежать казни. Взамен Хелен просит отвезти их на сушу.  ',
      shortDescription:
        'Люди в затопленном мире будущего жаждут найти островок земли. Приключенческий боевик с Кевином Костнером',
      logo: {
        url: 'https://avatars.mds.yandex.net/get-ott/223007/2a000001720d92c1ad49ed86cdeac7bee3ae/orig',
      },
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/1773646/eb2ac663-d552-42cc-b8d3-98d5683dfb47/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/1773646/eb2ac663-d552-42cc-b8d3-98d5683dfb47/x1000',
      },
      backdrop: {
        url: 'https://image.openmoviedb.com/kinopoisk-ott-images/200035/2a000001616b9a5b431179c277084672ac47/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-ott-images/200035/2a000001616b9a5b431179c277084672ac47/x1000',
      },
      rating: {
        kp: 7.639,
        imdb: 6.3,
        filmCritics: 5.5,
        russianFilmCritics: 0,
        await: null,
      },
      votes: {
        kp: 165581,
        imdb: 211635,
        filmCritics: 66,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 134,
      internalRating: 7.639,
      internalVotes: 165581,
      isSeries: false,
      ticketsOnSale: false,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: 'pg13',
      ageRating: 12,
      top10: null,
      top250: null,
      typeNumber: 1,
      status: null,
    },
    {
      internalNames: [],
      name: 'Водный мир острова Комодо',
      alternativeName: 'Waterwold of Komodo',
      enName: '',
      year: 2021,
      genres: [{ name: 'документальный' }],
      countries: [{ name: 'Германия' }],
      releaseYears: [{ start: 2021, end: 2021 }],
      id: 6065011,
      externalId: null,
      names: [],
      type: 'tv-series',
      description: '',
      shortDescription: '',
      logo: null,
      poster: null,
      backdrop: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 2,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 0,
      internalRating: 0,
      internalVotes: 2,
      isSeries: true,
      ticketsOnSale: false,
      totalSeriesLength: null,
      seriesLength: 45,
      ratingMpaa: null,
      ageRating: 16,
      top10: null,
      top250: null,
      typeNumber: 2,
      status: 'completed',
    },
    {
      internalNames: [],
      name: 'Водный мир Африки',
      alternativeName: 'Waterworld Africa',
      enName: '',
      year: 2015,
      genres: [{ name: 'документальный' }],
      countries: [{ name: 'США' }],
      releaseYears: [{ start: 2015, end: 2016 }],
      id: 4537485,
      externalId: { kpHD: null, imdb: 'tt6416330' },
      names: [],
      type: 'tv-series',
      description:
        'В Африке, где есть пресноводные леса, соленые озера и разнообразные дельты, одни из самых важных водно-болотных угодий и рек в мире. Узнайте, что скрывается под поверхностью реки Конго и в дельте реки Окаванго в Ботсване, и посмотрите, кто путешествовал, чтобы получить напиток из драгоценных, но опасных пойм.',
      shortDescription: '',
      logo: { url: null },
      poster: { url: null, previewUrl: null },
      backdrop: { url: null, previewUrl: null },
      rating: {
        kp: 0,
        imdb: 8.3,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 2,
        imdb: 10,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 0,
      internalRating: 8.3,
      internalVotes: 2,
      isSeries: true,
      ticketsOnSale: false,
      totalSeriesLength: null,
      seriesLength: 46,
      ratingMpaa: null,
      ageRating: null,
      top10: null,
      top250: null,
      typeNumber: 2,
      status: 'completed',
    },
    {
      internalNames: [
        'Путешествие в водный мир',
        'Stormworld',
        'Планетата на бурите',
      ],
      name: 'Путешествие в водный мир',
      alternativeName: 'Stormworld',
      enName: '',
      year: 2009,
      genres: [{ name: 'фантастика' }, { name: 'фэнтези' }],
      countries: [{ name: 'Австралия' }, { name: 'Канада' }],
      releaseYears: [{ start: 2009, end: 2009 }],
      id: 499970,
      externalId: { imdb: 'tt1132616', tmdb: 30803, kpHD: null },
      names: [
        { name: 'Путешествие в водный мир' },
        { name: 'Stormworld' },
        { name: 'Планетата на бурите', language: 'BG', type: null },
      ],
      type: 'tv-series',
      description:
        'Отправляясь покататься на катере, Джейсон и Ли же представить себе не могли, чем закончится их прогулка. Угодив в межпространственную бурю, ребята оказались... в параллельной вселенной! Здесь все по-другому — нет больших городов, нет ресторанов, школ, гостиниц и родителей! \r\n\r\nЗато тут три солнца, дикие берега, воинствующие народы, бушующие штормы и каждый глоток питьевой воды на вес золота. Здесь надо бороться и побеждать. Джейсону и Ли придется стать настоящими мужчинами, чтобы выжить в Водном мире и попытаться найти дорогу домой...',
      shortDescription: '',
      logo: { url: null },
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/1599028/30d306e1-4a34-4a9c-85d7-2f544d4635a6/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/1599028/30d306e1-4a34-4a9c-85d7-2f544d4635a6/x1000',
      },
      backdrop: { url: null, previewUrl: null },
      rating: {
        kp: 0,
        imdb: 6.5,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 66,
        imdb: 107,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 0,
      internalRating: 6.5,
      internalVotes: 66,
      isSeries: true,
      ticketsOnSale: false,
      totalSeriesLength: null,
      seriesLength: 24,
      ratingMpaa: null,
      ageRating: 12,
      top10: null,
      top250: null,
      typeNumber: 2,
      status: 'completed',
    },
    {
      internalNames: ['Война и мир', 'War & Peace'],
      name: 'Война и мир',
      alternativeName: 'War & Peace',
      enName: '',
      year: 2016,
      genres: [
        { name: 'драма' },
        { name: 'мелодрама' },
        { name: 'военный' },
        { name: 'история' },
      ],
      countries: [{ name: 'Великобритания' }],
      releaseYears: [{ start: 2016, end: 2016 }],
      id: 893150,
      externalId: {
        imdb: 'tt3910804',
        tmdb: 64099,
        kpHD: '4cbc54fc6477f88c9ad83017c4eeed17',
      },
      names: [{ name: 'Война и мир' }, { name: 'War & Peace' }],
      type: 'tv-series',
      description:
        'Действие сериала развивается в России XIX века, охватывая период с 1805 по 1812 годы. В основу сюжета положен роман Льва Толстого «Война и мир», основное внимание сфокусировано на судьбах Пьера Безухова, Андрея Болконского и Наташи Ростовой.',
      shortDescription:
        'BBC переосмысливает русскую классику. Удачная и живая экранизация романа Толстого с пронзительным Полом Дано',
      logo: {
        url: 'https://avatars.mds.yandex.net/get-ott/2439731/2a0000017224de5c1326ffd6735da06a6715/orig',
      },
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/1900788/ecbb3822-ee34-42f6-8480-e0920b41a050/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/1900788/ecbb3822-ee34-42f6-8480-e0920b41a050/x1000',
      },
      backdrop: {
        url: 'https://image.openmoviedb.com/kinopoisk-ott-images/239697/2a00000164d723df36e6d66cd95ffb5fcfcf/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-ott-images/239697/2a00000164d723df36e6d66cd95ffb5fcfcf/x1000',
      },
      rating: {
        kp: 8.015,
        imdb: 8.1,
        filmCritics: 0,
        russianFilmCritics: 87.5,
        await: null,
      },
      votes: {
        kp: 84522,
        imdb: 26920,
        filmCritics: 0,
        russianFilmCritics: 8,
        await: 0,
      },
      movieLength: 0,
      internalRating: 8.015,
      internalVotes: 84522,
      isSeries: true,
      ticketsOnSale: false,
      totalSeriesLength: 377,
      seriesLength: 60,
      ratingMpaa: null,
      ageRating: 18,
      top10: null,
      top250: null,
      typeNumber: 2,
      status: 'completed',
    },
    {
      internalNames: ['Война и мир'],
      name: 'Война и мир',
      alternativeName: '',
      enName: '',
      year: 1965,
      genres: [
        { name: 'драма' },
        { name: 'мелодрама' },
        { name: 'военный' },
        { name: 'история' },
      ],
      countries: [{ name: 'СССР' }],
      releaseYears: [{ start: 1965, end: 1965 }],
      id: 38898,
      externalId: { kpHD: 'd5739def19194c7eb7dbd128e49a0426' },
      names: [
        {
          name: 'Война и мир',
          language: 'RU',
          type: 'Russian title on kinopoisk',
        },
      ],
      type: 'tv-series',
      description:
        'История нескольких дворянских семей на фоне событий в Российской империи времен Наполеоновских войн.',
      shortDescription:
        'Судьбы дворян переплетаются в эпоху Наполеоновских войн. Шедевр Сергея Бондарчука, удостоенный премии «Оскар»',
      logo: null,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/4303601/10e216b8-b29c-4d12-a0cc-381cf3fbab64/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/4303601/10e216b8-b29c-4d12-a0cc-381cf3fbab64/x1000',
      },
      backdrop: {
        url: 'https://image.openmoviedb.com/kinopoisk-ott-images/223007/2a0000018b7231cca4a5498ca972e537ce22/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-ott-images/223007/2a0000018b7231cca4a5498ca972e537ce22/x1000',
      },
      rating: {
        kp: 8.1,
        imdb: 8.3,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: null,
      },
      votes: {
        kp: 57267,
        imdb: 8524,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 0,
      internalRating: 8.1,
      internalVotes: 57267,
      isSeries: true,
      ticketsOnSale: false,
      totalSeriesLength: 403,
      seriesLength: 103,
      ratingMpaa: 'g',
      ageRating: 18,
      top10: null,
      top250: null,
      typeNumber: 2,
      status: 'completed',
    },
  ],
  total: 1000,
  limit: 6,
  page: 1,
  pages: 167,
};

export default class App extends Component {
  state = {};

  render() {
    return (
      <div className='main'>
        <MoviesList moviesList={list.docs} />
      </div>
    );
  }
}
